services:
  frontend:
    image: frontend-prod:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: portfolio-frontend-prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production