services:

  frontend:
    image: frontend-dev:latest
    container_name: frontend-dev-container
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

    volumes:
      - ./:/app:rw
      - frontend_dev_node_modules:/app/node_modules
      - frontend_dev_next:/app/.next
      - frontend_dev_pnpm:/pnpm

    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - CI=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200

    # Instalaci√≥n y arranque en modo dev
    command: sh -c "pnpm config set store-dir /pnpm/store && pnpm install && pnpm run dev"

volumes:
  frontend_dev_node_modules:
  frontend_dev_next:
  frontend_dev_pnpm:

