services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: backend-dev-container
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app:rw
      - backend_dev_node_modules:/app/node_modules
      - backend_dev_pnpm:/pnpm
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - CI=true
    command: sh -c "pnpm config set store-dir /pnpm/store && pnpm install && pnpm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: frontend-dev-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:rw
      - frontend_dev_node_modules:/app/node_modules
      - frontend_dev_next:/app/.next
      - frontend_dev_pnpm:/pnpm
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - CI=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
    command: sh -c "pnpm config set store-dir /pnpm/store && pnpm install && pnpm run dev"

volumes:
  backend_dev_node_modules:
  backend_dev_pnpm:
  frontend_dev_node_modules:
  frontend_dev_next:
  frontend_dev_pnpm:
